AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  POC of how we might implement the backend for Editarrr level storage
  
Globals:
  Function:
    Timeout: 10

Resources:
  DDBHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dynamo-handler/
      Handler: app.handler
      Runtime: nodejs18.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LevelsTable
      Events:
        CreateLevel:
          Type: HttpApi
          Properties:
            Path: /levels
            Method: POST
        GetAllLevels:
          Type: HttpApi
          Properties:
            Path: /levels
            Method: GET
        GetLevel:
          Type: HttpApi
          Properties:
            Path: /levels/{id}
            Method: GET
        UpdateLevel:
          Type: HttpApi
          Properties:
            Path: /levels/{id}
            Method: PUT
        DeleteAnLevel:
          Type: HttpApi
          Properties:
            Path: /levels/{id}
            Method: DELETE

  LevelsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: levels-table
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: lastUpdated
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
      - IndexName: StatusLastUpdatedIndex
        KeySchema:
          - AttributeName: "status"
            KeyType: "HASH"
          - AttributeName: "lastUpdated"
            KeyType: "RANGE"
        Projection:
          ProjectionType: "ALL"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

Outputs:
  ApiEndpoint:
    Description: "The invoke URL for our HTTP API"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/levels"
  Function:
    Description: "DynamoDB handler function ARN"
    Value: !GetAtt DDBHandlerFunction.Arn
