AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Foo:
    Type: String

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: function.handler
      Runtime: nodejs18.x
      Environment:
        Variables:
          Foo: !Ref Foo
      Events:
        CreateLevel:
          Type: HttpApi
          Properties:
            Path: /levels
            Method: POST
            Auth:
              Authorizer: NONE
        GetAllLevels:
          Type: HttpApi
          Properties:
            Path: /levels
            Method: GET
            Auth:
              Authorizer: NONE
        GetLevel:
          Type: HttpApi
          Properties:
            Path: /levels/{id}
            Method: GET
            Auth:
              Authorizer: NONE
        UpdateLevel:
          Type: HttpApi
          Properties:
            Path: /levels/{id}
            Method: PUT
            Auth:
              Authorizer: NONE
        DeleteAnLevel:
          Type: HttpApi
          Properties:
            Path: /levels/{id}
            Method: DELETE
            Auth:
              Authorizer: NONE
